# Generated by Django 5.0.6 on 2024-06-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField()),
                ('coin_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('price_change', models.DecimalField(decimal_places=10, max_digits=20)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=20)),
                ('market_cap_rank', models.IntegerField()),
                ('volume', models.DecimalField(decimal_places=2, max_digits=20)),
                ('volume_rank', models.IntegerField()),
                ('volume_change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('circulating_supply', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_supply', models.DecimalField(decimal_places=2, max_digits=20)),
                ('diluted_market_cap', models.DecimalField(decimal_places=2, max_digits=20)),
                ('contracts', models.JSONField()),
                ('official_links', models.JSONField()),
                ('socials', models.JSONField()),
            ],
        ),
    ]
